spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/deployops_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false