# Para produccion se usan variables como "username = {DB_USER}" y se guardan dentro de application-dev.properties
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/deployops_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false